-- CREACIÓN DE LA TABLA GERENTE 
CREATE TABLE HOSPITALESDB.GERENTE(
    idGerente NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descGerente VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA CONDICIÓN
CREATE TABLE HOSPITALESDB.CONDICION(
    idCondicion  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descCondicion VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA SEDE
CREATE TABLE HOSPITALESDB.SEDE(
    idSede NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descSede VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA PROVINCIA
CREATE TABLE HOSPITALESDB.PROVINCIA(
    idProvincia NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descProvincia VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA DISTRITO
CREATE TABLE HOSPITALESDB.DISTRITO(
    idDistrito NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idProvincia NUMBER NOT NULL,
    descDistrito VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE,
    FOREIGN KEY (idProvincia) REFERENCES HOSPITALESDB.PROVINCIA(idProvincia)
);

-- CREACIÓN DE LA TABLA HOSPITAL
CREATE TABLE HOSPITALESDB.HOSPITAL(
    idHospital NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idDistrito NUMBER NOT NULL,
    Nombre VARCHAR2(100) NOT NULL,
    Antiguedad NUMBER NOT NULL,
    Area NUMBER(5,2) NOT NULL,
    idSede NUMBER NOT NULL,
    idGerente NUMBER  NOT NULL,
    idCondicion NUMBER  NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE,
    fechaModificacion DATE  NULL,
    FOREIGN KEY (idDistrito) REFERENCES HOSPITALESDB.DISTRITO(idDistrito),
    FOREIGN KEY (idSede) REFERENCES HOSPITALESDB.SEDE(idSede),
    FOREIGN KEY (idGerente) REFERENCES HOSPITALESDB.GERENTE(idGerente),
    FOREIGN KEY (idCondicion) REFERENCES HOSPITALESDB.CONDICION(idCondicion)
);




