-- CREACIÓN DE LA TABLA GERENTE 
CREATE TABLE HOSPITALESDB.GERENTE(
    idGerente NUMBER PRIMARY KEY,
    descGerente VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA CONDICIÓN
CREATE TABLE HOSPITALESDB.CONDICION(
    idCondicion NUMBER PRIMARY KEY,
    descCondicion VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA SEDE
CREATE TABLE HOSPITALESDB.SEDE(
    idSede NUMBER PRIMARY KEY,
    descSede VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA PROVINCIA
CREATE TABLE HOSPITALESDB.PROVINCIA(
    idProvincia NUMBER PRIMARY KEY,
    descProvincia VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA DISTRITO
CREATE TABLE HOSPITALESDB.DISTRITO(
    idDistrito NUMBER PRIMARY KEY,
    idProvincia NUMBER NOT NULL,
    descDistrito VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE,
    FOREIGN KEY (idProvincia) REFERENCES HOSPITALESDB.PROVINCIA(idProvincia)
);

-- CREACIÓN DE LA TABLA HOSPITAL
CREATE TABLE HOSPITALESDB.HOSPITAL(
    idHospital NUMBER PRIMARY KEY,
    idDistrito NUMBER NOT NULL,
    Nombre VARCHAR2(100) NOT NULL,
    Antiguedad NUMBER NOT NULL,
    Area NUMBER(5,2) NOT NULL,
    idSede NUMBER NOT NULL,
    idGerente NUMBER  NOT NULL,
    idCondicion NUMBER  NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE,
    FOREIGN KEY (idDistrito) REFERENCES HOSPITALESDB.DISTRITO(idDistrito),
    FOREIGN KEY (idSede) REFERENCES HOSPITALESDB.SEDE(idSede),
    FOREIGN KEY (idGerente) REFERENCES HOSPITALESDB.GERENTE(idGerente),
    FOREIGN KEY (idCondicion) REFERENCES HOSPITALESDB.CONDICION(idCondicion)
);

-- CREACIÓN DE SECUENCIAS PARA GENERAR IDS AUTOMÁTICOS
CREATE SEQUENCE HOSPITALESDB.SEQ_GERENTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HOSPITALESDB.SEQ_CONDICION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HOSPITALESDB.SEQ_PROVINCIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HOSPITALESDB.SEQ_DISTRITO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HOSPITALESDB.SEQ_SEDE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HOSPITALESDB.SEQ_HOSPITAL START WITH 1 INCREMENT BY 1;

-- CREACIÓN DE TRIGGERS PARA ASIGNAR AUTOMÁTICAMENTE LOS IDS
CREATE OR REPLACE TRIGGER HOSPITALESDB.TRG_GERENTE
BEFORE INSERT ON HOSPITALESDB.GERENTE
FOR EACH ROW
BEGIN
    SELECT HOSPITALESDB.SEQ_GERENTE.NEXTVAL INTO :NEW.idGerente FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER HOSPITALESDB.TRG_CONDICION
BEFORE INSERT ON HOSPITALESDB.CONDICION
FOR EACH ROW
BEGIN
    SELECT HOSPITALESDB.SEQ_CONDICION.NEXTVAL INTO :NEW.idCondicion FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER HOSPITALESDB.TRG_SEDE
BEFORE INSERT ON HOSPITALESDB.SEDE
FOR EACH ROW
BEGIN
    SELECT HOSPITALESDB.SEQ_SEDE.NEXTVAL INTO :NEW.idSede FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER HOSPITALESDB.TRG_PROVINCIA
BEFORE INSERT ON HOSPITALESDB.PROVINCIA
FOR EACH ROW
BEGIN
    SELECT HOSPITALESDB.SEQ_PROVINCIA.NEXTVAL INTO :NEW.idProvincia FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER HOSPITALESDB.TRG_DISTRITO
BEFORE INSERT ON HOSPITALESDB.DISTRITO
FOR EACH ROW
BEGIN
    SELECT HOSPITALESDB.SEQ_DISTRITO.NEXTVAL INTO :NEW.idDistrito FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER HOSPITALESDB.TRG_HOSPITAL
BEFORE INSERT ON HOSPITALESDB.HOSPITAL
FOR EACH ROW
BEGIN
    SELECT HOSPITALESDB.SEQ_HOSPITAL.NEXTVAL INTO :NEW.idHospital FROM DUAL;
END;
/
