-- CREACIÓN DE LA TABLA GERENTE 
CREATE TABLE GERENTE(
    idGerente NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descGerente VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA CONDICIÓN
CREATE TABLE CONDICION(
    idCondicion  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descCondicion VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA SEDE
CREATE TABLE SEDE(
    idSede NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descSede VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA PROVINCIA
CREATE TABLE PROVINCIA(
    idProvincia NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    descProvincia VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE
);
-- CREACIÓN DE LA TABLA DISTRITO
CREATE TABLE DISTRITO(
    idDistrito NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idProvincia NUMBER NOT NULL,
    descDistrito VARCHAR2(100) NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE,
    FOREIGN KEY (idProvincia) REFERENCES HOSPITALESDB.PROVINCIA(idProvincia)
);

-- CREACIÓN DE LA TABLA HOSPITAL
CREATE TABLE HOSPITAL(
    idHospital NUMBER  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    idDistrito NUMBER NOT NULL,
    Nombre VARCHAR2(100) NOT NULL,
    Antiguedad NUMBER NOT NULL,
    Area NUMBER(5,2) NOT NULL,
    idSede NUMBER NOT NULL,
    idGerente NUMBER  NOT NULL,
    idCondicion NUMBER  NOT NULL,
    fechaRegistro DATE DEFAULT SYSDATE,
    fechaModificacion DATE  NULL,
    FOREIGN KEY (idDistrito) REFERENCES DISTRITO(idDistrito),
    FOREIGN KEY (idSede) REFERENCES SEDE(idSede),
    FOREIGN KEY (idGerente) REFERENCES GERENTE(idGerente),
    FOREIGN KEY (idCondicion) REFERENCES CONDICION(idCondicion)
);


